### ISSUE TITLE
fix-db-relations

### ISSUE THREAD

**Issue by 2k4sm** [sst-product-team/zolo-booky-backend#31]
There is error in database relations.

we have to create mappings in order to fix it.

**Comment by 2k4sm** [comment]
@skushagra  Regarding the relations.

- Each user has ability to post multiple books so for books and users many to one relationship is best.
- For appeals each appeal will link one book and one borrower so one to one relationship should be used ig.

I was trying to fix it but still there is no progress.

**Comment by 2k4sm** [comment]
@skushagra maybe we'll have to rethink appeals.

**Comment by skushagra** [comment]
I'll check and get it fixed by tomorrow.
